image: docker:latest
services: 
  - docker:dind
cache:
  key: ${CI_COMMIT_REF_SLUG}

variables:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  ENDPOINT: ${ENDPOINT}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

build:
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose && pip install --user awscli==1.17.7 && export PATH=/root/.local/bin:$PATH
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - eval $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})  
    - docker pull ${ENDPOINT}/bitovi/bitops:latest
    - docker run --rm --name bitops -e CLUSTER_NAME=qa-bitops -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"" AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}" -e ENVIRONMENT=opscruise-test3 -e HELM_CHARTS=true -e KUBECONFIG_BASE64="${KUBECONFIG_BASE64} "-v $(pwd):/opt/bitops_deployment bitops:latest


 
