image: docker:latest
services: 
  - docker:dind
cache:
  key: ${CI_COMMIT_REF_SLUG}

build:
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose up -d --build && sleep 5
    - docker-compose exec -T bitops /bin/bash -cx "scripts/deploy/run_deployments.sh --helm-charts /opt/deploy/qa/microservices/helm-chart --environment qa --ansible-directory /opt/deploy/ansible/hello-ansible.yml"
    - docker-compose down

