image: docker:latest
services: 
  - docker:dind
cache:
  key: ${CI_COMMIT_REF_SLUG}

build:
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - echo "Look at - $AWS_DEFAULT_REGION"
    - docker-compose up -d --build
    - docker-compose exec -T bitops /bin/bash -cx "scripts/deploy/run_deployments.sh --environment qa --ansible-directory /opt/deploy/ansible/hello-ansible.yml --external-helm-charts loki,loki-stack,https://grafana.github.io/loki/charts"
    - docker-compose down

