image: docker:latest
services: 
  - docker:dind
cache:
  key: ${CI_COMMIT_REF_SLUG}

build:
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose up -d --build && sleep 5
    - docker-compose exec -T bitops /bin/bash -c "cd ./terraform && /usr/local/bin/terraform init && /usr/local/bin/terraform plan"
    - docker-compose exec -T bitops /bin/bash -c "./scripts/helm/helm_deploy.sh"
    - docker-compose down

