language: python3

services:
- docker

before_install:
- sudo apt-get update
- sudo apt-get remove -y docker docker-engine docker.io containerd runc
- sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo apt-key fingerprint 0EBFCD88
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update -y
- sudo apt-get install -y docker-ce docker-ce-cli containerd.io
- pip install awscli
- which aws
- export PATH=$PATH:$HOME/.local/bin

build:
- eval $(aws ecr get-login-password | docker login --username AWS --password-stdin 832297766686.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/bitovi/bitops:latest)
- docker build -t bitovi/bitops .
- docker tag bitovi/bitops:latest 832297766686.dkr.ecr.$AWS_DEFAULT_REGION..amazonaws.com/bitovi/bitops:latest
- docker push 832297766686.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/bitovi/bitops:latest

script: 
- docker run --rm --name bitops bitops:latest
