# Secrets Manager (for holding sensitive data) - Options are: vault, ssm or none
secrets_manager:
  value: none

# Image Repository - Options: ecr, docker, quay, gcr
image_repository:
  value: ecr
  
# Specify Kubernetes version: Options: Kubernetes 1.11, 1.12, 1.13, and 1.14
kubectl:
  version: 1.13.7

# Example: prod, qa
environment:
  default: qa


cloud_platform:
  - aws:
    name: aws
    enabled: true
    region: us-east-2

# Specify Terraform version. Options: Terraform 0.11.14 or 0.12.21
terraform:
  version: 0.11.14

# Specify Helm version. Options: 2 or 3
helm:
  version: 3.2.0
  namespace: default
  
ansible:
  version: 2.5

