version: '3.7'
services:
  bitops:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - KUBECONFIG_BASE64=${KUBECONFIG_BASE64}
    volumes:
      - .:/opt/bitops
    entrypoint: /opt/bitops/entrypoint.sh

