helm:
  type: object
  properties:
    cli:
      type: object
      properties:
        namespace:
          type: string
          parameter: namespace
          export_env: NAMESPACE
          required: true
        timeout:
          type: string
          parameter: timeout
          export_env: TIMEOUT
          default: "500s"
        debug:
          type: boolean
          parameter: debug
          export_env: HELM_DEBUG
        atomic:
          type: boolean
          parameter: atomic
        force:
          type: boolean
          parameter: force
        dry-run:
          type: boolean
          parameter: dry-run
    options:
      type: object
      properties:
        skip-deploy:
          type: boolean
          terminal: true
          parameter: skip-deploy
          export_env: SKIP_DEPLOY
        release-name:
          type: string
          export_env: HELM_RELEASE_NAME
        kubeconfig:
          type: object
          properties:
            path:
              type: string
              export_env: KUBE_CONFIG_PATH
            fetch:
              type: object
              properties:
                fetch_kubeconfig: 
                  type: boolean
                  default: true
                  export_env: FETCH_KUBECONFIG
                cluster-name:
                  type: string
                  export_env: CLUSTER_NAME
        # cluster-name:
        #   type: string
        #   export_env: CLUSTER_NAME
        # fetch-kubeconfig:
        #   type: boolean
        #   export_env: FETCH_KUBECONFIG
        #   default: true
    plugins:
      type: object
      properties:
        s3:
          type: object
          properties:
            region:
              type: string
              export_env: HELM_PLUGIN_S3_REGION
            bucket:
              type: string
              export_env: HELM_CHARTS_S3_BUCKET
