version: 2.1
workflows:
  bitops:
    jobs:
      - build:
          context: bitops
          filters:
            branches:
              only:
                - cleanup-scripts
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      # registry setup
      BITOPS_PUBLISH_ECR: "1"
      REGISTRY_URL: "$ECR_ENDPOINT/bitovi/bitops"
      AWS_ACCESS_KEY_ID: "$BITOPS_AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "$BITOPS_AWS_SECRET_ACCESS_KEY"

      # publish setup
      BITOPS_DOCKER_IMAGE_PUBLISH_TAG: "cleanup-scripts"
      BITOPS_DOCKER_IMAGE_PUBLISH_SKIP_SHA: "1"
      BITOPS_DOCKER_IMAGE_NAME: "$CIRCLE_PROJECT_REPONAME"
      BITOPS_GIT_TAG: "$CIRCLE_TAG"
      BITOPS_GIT_SHA: "$CIRCLE_SHA1"
      BITOPS_GIT_BRANCH: "$CIRCLE_BRANCH"
      BITOPS_GIT_BASE_BRANCH: "master"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            ./scripts/ci/install.sh
      - run:
          name: Run tests
          command: |
            ./scripts/ci/test.sh
      - deploy:
          name: Publish docker image
          command: |
            ./scripts/ci/publish.sh

